###
GET http://localhost:3000/api/roles

###
POST http://localhost:3000/api/roles HTTP/2
Content-Type: application/json

{
  "name": "user"
}

###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users HTTP/2
Content-Type: application/json

{
  "email": "electrohumanic@gmail.com",
  "password": "simple_owner_password",
  "roleId": 1
}

###
DELETE http://localhost:3000/api/users/a37be305-6f32-4659-aebc-eec1f47e31d0
###
GET http://localhost:3000/api/cats

###
POST http://localhost:3000/api/cats HTTP/2
Content-Type: application/json

{
  "name": "Belka",
  "sex": "f",
  "age": "ddd"
}

###
DELETE http://localhost:3000/api/cats/578c93b0-04bf-11ef-a9d0-8f9dacce840f


