###
GET http://localhost:3000/api/roles

###
POST http://localhost:3000/api/roles HTTP/2
Content-Type: application/json

{
  "name": "user"
}

###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users HTTP/2
Content-Type: application/json

{
  "email": "electrohumanic@gmail.com",
  "password": "simple_owner_password",
  "roleId": 1
}

###
DELETE http://localhost:3000/api/users/a37be305-6f32-4659-aebc-eec1f47e31d0
###
GET http://localhost:3000/api/cats

###
POST http://localhost:3000/api/cats HTTP/2
Content-Type: application/json

{
  "name": "Belka",
  "sex": "f",
  "age": 13
}

###
DELETE http://localhost:3000/api/cats/a27bd090-0648-11ef-99bd-1721d91df967

###
GET http://localhost:3000/api/colors

###
POST http://localhost:3000/api/colors
Content-Type: application/json

{
  "name": "серый"
}

###
PATCH http://localhost:3000/api/colors/c3473ab0-08b6-11ef-8f11-b37f2d06b4b7
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

персиковый
--WebAppBoundary--

###
DELETE localhost:3000/api/colors/cb009da0-08b6-11ef-8f11-b37f2d06b4b7
